version: "3"

services:
  clock:
    image: "bmiddha/simple-js-clock:latest"
    ports: 
      - ${PORT}:8080
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
      - ${SSL_DIR}:/usr/src/app/ssl