version: "3"

services:
  clock:
    image: "acm-uic/simple-ts-clock:latest"
    build: .
    restart: always
    ports: 
      - ${PORT}:8080
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
      - ${TLS_DIR}:/usr/src/app/ssl
