name: Biome JS Code Quality Checks

on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        # TODO: Check for all issues, not just changed files, once we're handling them better (https://github.com/acm-uic/simple-ts-clock/issues/34).
        # (That is, switch to `biome ci .`)uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci --changed .
