name: Docker CI

on: push

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build-image
      uses: actions/docker/cli@master
      with:
        args: build .
